// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xqvipdjcmbuwagjcroda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhxdmlwZGpjbWJ1d2FnamNyb2RhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MTUxNDgsImV4cCI6MjA2NzA5MTE0OH0.oPGZngN5AxtWDQQgq_M0rcBkIzRNhbgpKgCeUIAiaq0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});